---
title: Cayman theme
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics: 
theme: jekyll-theme-cayman
